### PR TITLE
The next web clone project

### PR DESCRIPTION
**Pull request by PhiPhiPhi**
Building with Responsive Design Project completed. please review. Thanks!

### CODE REVIEW

**Comment by shloch** [comment]
### PR under review by SHEY Louis CHIA

**Comment by shloch** [comment]
Hello @PhiPhiPhi 

I had a hard time distinguishing yours with the original, this is perfect.

It's also the longest code i have seen so far (above 2000 lines lol )

[correct this one small thing and everything will be perfect]

Screen Shot 2019-11-19 at 11 48 20 AM

look at the timer as we test your responsiveness, it overlaps in a not-so-pleasant way. You could make the font smaller, or remove it already if there's no space

**Review by shloch — APPROVED** [review]
I count on you to know off the minor issue i presented above, to make it clean

## On my part, this project gets a thumbs up and is approved 😊👏👏

Happy coding 😊😊

**Comment by PhiPhiPhi** [comment]
Thank you!

**Pull request merged**
